name: district_picker_turkey_map
description: A district selector from turkish cities maps similar to city_picker_from_map
version: 0.0.2
homepage: https://github.com/Fatih-Mehmet-Yuksel/district_picker_turkey_map

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  svg_path_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


 assets:
   - assets/maps/
